In [23]:
import numpy as np
import math
W = np.array([[1,1,1],[2,2,2]])
X = np.array([[0,0,-1],[0,1,-1],[1,0,-1],[1,1,-1]])
print(W)
print(X)
Output = X[0,:]
print(Output)

[[1 1 1]
 [2 2 2]]
[[ 0  0 -1]
 [ 0  1 -1]
 [ 1  0 -1]
 [ 1  1 -1]]
[ 0  0 -1]


In [29]:
Output =np.sum(W*X[0,:],axis = 1)
print(Output)
Outpu2 = 1/(1+np.exp(-Output))
Output2 = Outpu2.reshape((-1,1))
print(Output2)

[-1 -2]
[[0.26894142]
 [0.11920292]]


In [33]:
W2 = np.array([[1,1,1]])
X2 = np.array([[0,0,-1]])
Ool = np.sum(W2*X2)
Ool =  1/(1+np.exp(-Ool))
Ool

0.2689414213699951